--drop table if exists customerdata;
--drop table if exists profession_customerdata;
--drop table if exists extracteddata;
--drop table if exists knowledge;
--drop table if exists profession;
--drop table if exists profession_knowledge;
--drop table if exists summary;

alter table knowledge alter column id type bigint auto_increment;

insert into knowledge (id, value, knowledgebasetype, archetype) values (1, 'junior php programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (2, 'php programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (3, 'senior php programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (4, 'junior jee programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (5, 'jee programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (6, 'senior jee programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (7, 'junior java programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (8, 'java programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (9, 'junior programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (10, 'mid programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (11, 'senior programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (12, 'junior developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (13, 'mid developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (14, 'senior developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (15, 'junior jee developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (16, 'mid jee developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (17, 'senior jee developer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (18, 'junior administrator','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (19, 'administrator','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (20, 'senior administrator','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (21, 'product manager','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (22, 'product specialist','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (23, 'business development director','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (24, 'business development manager','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (25, 'project development specialist','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (26, 'director','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (27, 'senior program manager','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (28, 'graphic designer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (29, 'team lider it','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (30, 'it manager','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (31, 'it specialist','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (32, 'lead programmer','EXPERIENCE','POSITION');
insert into knowledge (id, value, knowledgebasetype, archetype) values (33, 'team leader','EXPERIENCE','POSITION');

insert into knowledge (id, value, knowledgebasetype, archetype) values (34, 'blue media','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (35, 'BlueMedia','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (36, 'spartez','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (37, 'atlassian','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (38, 'apple','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (39, 'microsoft','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (40, 'google','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (41, 'intel','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (42, 'asseco','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (43, 'comarch','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (44, 'misys','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (45, 'kinos','EXPERIENCE','FIRM');
insert into knowledge (id, value, knowledgebasetype, archetype) values (46, 'atena','EXPERIENCE','FIRM');

insert into knowledge (id, value, knowledgebasetype, archetype) values (47, 'analysis of project requirements','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (48, 'creation of system architecture','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (49, 'system design','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (50, 'implementation','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (51, 'testing','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (52, 'creating documentation','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (53, 'code review','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (54, 'programming','EXPERIENCE','RESPONSIBILITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (55, 'continous integration','EXPERIENCE','RESPONSIBILITY');

insert into knowledge (id, value, knowledgebasetype, archetype) values (56, 'Uniwersytet Warszawski','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (57, 'Uniwersytet w Białymstoku','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (58, 'Uniwersytet Gdański','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (59, 'Uniwersytet im. Adama Mickiewicza w Poznaniu','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (60, 'Uniwersytet Jagielloński w Krakowie','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (61, 'Uniwersytet Łódzki','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (62, 'Uniwersytet Marii Curie-Skłodowskiej w Lublinie','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (63, 'Uniwersytet Mikołaja Kopernika w Toruniu','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (64, 'Uniwersytet Opolski','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (65, 'Uniwersytet Szczeciński','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (66, 'Uniwersytet Śląski w Katowicach','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (67, 'Uniwersytet Rzeszowski','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (68, 'Uniwersytet Warmińsko-Mazurski w Olsztynie','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (69, 'Uniwersytet Wrocławski','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (70, 'Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (71, 'Uniwersytet Zielonogórski','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (72, 'Uniwersytet Kazimierza Wielkiego w Bydgoszczy','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (73, 'Uniwersytet Jana Kochanowskiego w Kielcach','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (74, 'Uniwersytet Technologiczny w Szczecinie','EDUCATION','UNIWERSITY');
insert into knowledge (id, value, knowledgebasetype, archetype) values (75, 'Politechnika Warszawska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (76, 'Politechnika Białostocka','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (77, 'Akademia Techniczno-Humanistyczna w Bielsku -Białej','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (78, 'Politechnika Częstochowska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (79, 'Politechnika Gdańska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (80, 'Politechnika Śląska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (81, 'Politechnika Świętokrzyska w Kielcach','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (82, 'Politechnika Koszalińska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (83, 'Politechnika Krakowska im. Tadeusza Kościuszki','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (84, 'Politechnika Lubelska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (85, 'Politechnika Łódzka','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (86, 'Politechnika Opolska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (87, 'Politechnika Poznańska','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (88, 'Uniwersytet Technologiczno-Humanistyczny im. Kazimierza Pułaskiego w Radomiu','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (89, 'Politechnika Rzeszowska im. Ignacego Łukasiewicza','EDUCATION','POLYTECHNIC');
insert into knowledge (id, value, knowledgebasetype, archetype) values (90, 'Politechnika Wrocławska','EDUCATION','POLYTECHNIC');

insert into knowledge (id, value, knowledgebasetype, archetype) values (91, 'EJB','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (92, 'CDI','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (93, 'jboss','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (94, 'wildfly','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (95, 'activemq','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (96, 'webservice','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (97, 'jms','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (98, 'linux','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (99, 'tcp/ip','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (100, 'ipsec','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (101, 'vpn','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (102, 'Jee 6','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (103, 'Jee 7','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (104, 'prime faces','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (105, 'jsf','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (106, 'jsp','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (107, 'servlet','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (108, 'ibm mq','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (109, 'Jee','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (110, 'java','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (111, 'spring','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (112, 'maven','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (113, 'tomcat','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (114, 'glassfish','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (115, 'websphere','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (116, 'maven','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (117, 'sql','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (118, 'posgresql','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (119, 'mysql','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (120, 'sql','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (121, 'git','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (122, 'svn','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (123, 'jenkins','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (124, 'bamboo','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (125, 'teamcity','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (126, 'jira','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (127, 'apache camel','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (128, 'gradle','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (129, 'google guava','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (130, 'guava','SKILLS','TECHNICAL');
insert into knowledge (id, value, knowledgebasetype, archetype) values (131, 'apache commons','SKILLS','TECHNICAL');

insert into knowledge (id, value, knowledgebasetype, archetype) values (132, 'communicative','SKILLS','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (133, 'open','SKILLS','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (134, 'willing to work','SKILLS','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (135, 'eager to learn','SKILLS','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (136, 'bright','SKILLS','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (137, 'driving license','SKILLS','OTHER');

insert into knowledge (id, value, knowledgebasetype, archetype) values (138, 'good movie','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (139, 'good book','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (140, 'games','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (141, 'meet people','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (142, 'meeting new people','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (143, 'running','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (144, 'kitesurfing','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (145, 'windsurfing','INTEREST','OTHER');
insert into knowledge (id, value, knowledgebasetype, archetype) values (146, 'football','INTEREST','OTHER');

insert into profession (id, createtime, description) values ('JAVA', now(), 'Programista Java');
insert into profession (id, createtime, description) values ('ADMIN', now(), 'Administrator Sieci');
insert into profession (id, createtime, description) values ('PHP', now(), 'Programista Php');

insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 4 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 5 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 6 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 7 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 8 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 9 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 10 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 11 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 12 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 13 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 14 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 15 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 16 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 17 );

insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 21 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 22 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 23 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 24 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 25 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 26 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 27 );

insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 29 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 30 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 31 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 32 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 33 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 34 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 35 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 36 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 37 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 38 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 39 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 40 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 41 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 42 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 43 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 44 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 45 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 46 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 47 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 48 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 49 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 50 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 51 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 52 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 53 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 54 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 55 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 56 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 57 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 58 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 59 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 60 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 61 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 62 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 63 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 64 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 65 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 66 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 67 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 68 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 69 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 70 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 71 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 72 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 73 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 74 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 75 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 76 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 77 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 78 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 79 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 80 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 81 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 82 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 83 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 84 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 85 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 86 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 87 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 88 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 89 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 90 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 91 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 92 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 93 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 94 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 95 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 96 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 97 );

insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 102 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 103 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 104 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 105 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 106 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 107 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 108 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 109 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 110 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 111 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 112 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 113 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 114 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 115 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 116 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 117 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 118 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 119 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 120 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 121 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 122 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 123 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 124 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 125 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 126 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 127 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 128 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 129 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 130 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 131 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 132 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 133 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 134 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 135 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 136 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 137 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 138 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 139 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 140 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 141 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 142 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 143 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 144 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 145 );
insert into profession_knowledge (profession_id, knowledgelist_id) values ('JAVA', 146 );