insert into knowledge (value, knowledgebasetype, archetype) values ('junior php programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('php programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('senior php programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('junior jee programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('jee programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('senior jee programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('junior java programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('java programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('senior java programmer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('junior administrator','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('administrator','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('senior administrator','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('product manager','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('product specialist','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('business development director','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('business development manager','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('project development specialist','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('director','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('senior program manager','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('graphic designer','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('team lider it','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('it manager','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('it specialist','EXPIRIENCE','POSITION');
insert into knowledge (value, knowledgebasetype, archetype) values ('blue media','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('spartez','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('atlassian','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('apple','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('microsoft','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('google','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('intel','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('asseco','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('comarch','EXPIRIENCE','FIRM');
insert into knowledge (value, knowledgebasetype, archetype) values ('analysis of project requirements','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('creation of system architecture','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('system design','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('implementation','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('testing','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('creating documentation','EXPIRIENCE','RESPONSIBILITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Warszawski','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet w Białymstoku','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Gdański','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet im. Adama Mickiewicza w Poznaniu','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Jagielloński w Krakowie','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Łódzki','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Marii Curie-Skłodowskiej w Lublinie','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Mikołaja Kopernika w Toruniu','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Opolski','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Szczeciński','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Śląski w Katowicach','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Rzeszowski','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Warmińsko-Mazurski w Olsztynie','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Wrocławski','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Kardynała Stefana Wyszyńskiego w Warszawie','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Zielonogórski','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Kazimierza Wielkiego w Bydgoszczy','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Jana Kochanowskiego w Kielcach','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Technologiczny w Szczecinie','EDUCATION','UNIWERSITY');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Warszawska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Białostocka','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Akademia Techniczno-Humanistyczna w Bielsku -Białej','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Częstochowska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Gdańska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Śląska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Świętokrzyska w Kielcach','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Koszalińska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Krakowska im. Tadeusza Kościuszki','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Lubelska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Łódzka','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Opolska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Poznańska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Uniwersytet Technologiczno-Humanistyczny im. Kazimierza Pułaskiego w Radomiu','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Rzeszowska im. Ignacego Łukasiewicza','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('Politechnika Wrocławska','EDUCATION','POLYTECHNIC');
insert into knowledge (value, knowledgebasetype, archetype) values ('EJB','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('CDI','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('jboss','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('wildfly','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('activemq','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('webservice','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('jms','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('linux','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('tcp/ip','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('ipsec','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('vpn','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('Jee 6','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('Jee 7','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('prime faces','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('jsf','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('jsp','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('servlet','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('ibm mq','SKILLS','TECHNICAL');
insert into knowledge (value, knowledgebasetype, archetype) values ('communicative','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('open','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('willing to work','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('eager to learn','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('bright','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('driving license','SKILLS','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('good movie','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('good book','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('games','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('meet people','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('meeting new people','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('running','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('kitesurfing','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('windsurfing','INTEREST','OTHER');
insert into knowledge (value, knowledgebasetype, archetype) values ('football','INTEREST','OTHER');