-- DBCreate script

CREATE TABLE FILTEREDDATA (
  ID SERIAL  NOT NULL ,
  EDUCATION VARCHAR    ,
  EXPERIENCE VARCHAR    ,
  INTEREST VARCHAR    ,
  SKILLS VARCHAR      ,
PRIMARY KEY(ID));




CREATE TABLE KNOWLEDGEBASETYPE (
  ID SERIAL  NOT NULL ,
  DESCRIPTION VARCHAR    ,
  CREATETIME TIMESTAMP    ,
  POINTS INTEGER      ,
PRIMARY KEY(ID));




CREATE TABLE PROFESSION (
  ID SERIAL  NOT NULL ,
  CREATETIME TIMESTAMP    ,
  DESCRIPTION VARCHAR      ,
PRIMARY KEY(ID));




CREATE TABLE SUMMARY (
  ID SERIAL  NOT NULL ,
  CUSTOMERDATA_ID INTEGER    ,
  EDUCATIONPOINTS INTEGER    ,
  EXPERIENCEPOINTS INTEGER    ,
  INTERESTPOINTS INTEGER    ,
  SKILLSPOINTS INTEGER      ,
PRIMARY KEY(ID));




CREATE TABLE ARCHETYPE (
  ID SERIAL  NOT NULL ,
  DESCRIPTION VARCHAR    ,
  CREATETIME TIMESTAMP    ,
  POINTS INTEGER      ,
PRIMARY KEY(ID));




CREATE TABLE EXTRACTEDDATA (
  ID SERIAL  NOT NULL ,
  EDUCATION VARCHAR    ,
  EXPERIENCE VARCHAR    ,
  INTEREST VARCHAR    ,
  SKILLS VARCHAR      ,
PRIMARY KEY(ID));




CREATE TABLE KNOWLEDGE (
  ID SERIAL  NOT NULL ,
  KNOWLEDGEBASETYPE_ID VARCHAR   NOT NULL ,
  ARCHETYPE_ID INTEGER   NOT NULL ,
  VALUE VARCHAR      ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(ARCHETYPE_ID)
    REFERENCES ARCHETYPE(ID),
  FOREIGN KEY(KNOWLEDGEBASETYPE_ID)
    REFERENCES KNOWLEDGEBASETYPE(ID));


CREATE INDEX KNOWLEDGE_FKIndex1 ON KNOWLEDGE (ARCHETYPE_ID);
CREATE INDEX KNOWLEDGE_FKIndex2 ON KNOWLEDGE (KNOWLEDGEBASETYPE_ID);


CREATE INDEX IFK_Rel_08 ON KNOWLEDGE (ARCHETYPE_ID);
CREATE INDEX IFK_Rel_09 ON KNOWLEDGE (KNOWLEDGEBASETYPE_ID);


CREATE TABLE CUSTOMERDATA (
  ID SERIAL  NOT NULL ,
  EXTRACTEDDATA_ID INTEGER   NOT NULL ,
  FILTEREDDATA_ID INTEGER   NOT NULL ,
  PROFESSION_ID VARCHAR   NOT NULL ,
  SUMMARY_ID INTEGER   NOT NULL ,
  CREATETIME DATETIME    ,
  FIRSTNAME VARCHAR    ,
  LASTNAME VARCHAR    ,
  EMAIL VARCHAR    ,
  FILENAME VARCHAR    ,
  LASTMODIFIEDTIME DATETIME    ,
  PROCESSSTATUS VARCHAR    ,
  STOREDCV VARCHAR      ,
PRIMARY KEY(ID, EXTRACTEDDATA_ID, FILTEREDDATA_ID, PROFESSION_ID, SUMMARY_ID)        ,
  FOREIGN KEY(EXTRACTEDDATA_ID)
    REFERENCES EXTRACTEDDATA(ID),
  FOREIGN KEY(FILTEREDDATA_ID)
    REFERENCES FILTEREDDATA(ID),
  FOREIGN KEY(PROFESSION_ID)
    REFERENCES PROFESSION(ID),
  FOREIGN KEY(SUMMARY_ID)
    REFERENCES SUMMARY(ID));


CREATE INDEX CUSTOMERDATA_FKIndex2 ON CUSTOMERDATA (EXTRACTEDDATA_ID);
CREATE INDEX CUSTOMERDATA_FKIndex3 ON CUSTOMERDATA (FILTEREDDATA_ID);
CREATE INDEX CUSTOMERDATA_FKIndex3 ON CUSTOMERDATA (PROFESSION_ID);
CREATE INDEX CUSTOMERDATA_FKIndex4 ON CUSTOMERDATA (SUMMARY_ID);


CREATE INDEX IFK_Rel_06 ON CUSTOMERDATA (EXTRACTEDDATA_ID);
CREATE INDEX IFK_Rel_07 ON CUSTOMERDATA (FILTEREDDATA_ID);
CREATE INDEX IFK_Rel_08 ON CUSTOMERDATA (PROFESSION_ID);
CREATE INDEX IFK_Rel_10 ON CUSTOMERDATA (SUMMARY_ID);


CREATE TABLE PROFESSION_KNOWLEDGE (
  PROFESSION_ID VARCHAR   NOT NULL ,
  KNOWLEDGE_ID INTEGER   NOT NULL   ,
PRIMARY KEY(PROFESSION_ID, KNOWLEDGE_ID)    ,
  FOREIGN KEY(PROFESSION_ID)
    REFERENCES PROFESSION(ID),
  FOREIGN KEY(KNOWLEDGE_ID)
    REFERENCES KNOWLEDGE(ID));


CREATE INDEX PROFESSION_KNOWLEDGE_FKIndex1 ON PROFESSION_KNOWLEDGE (PROFESSION_ID);
CREATE INDEX PROFESSION_KNOWLEDGE_FKIndex2 ON PROFESSION_KNOWLEDGE (KNOWLEDGE_ID);


CREATE INDEX IFK_Rel_09 ON PROFESSION_KNOWLEDGE (PROFESSION_ID);
CREATE INDEX IFK_Rel_10 ON PROFESSION_KNOWLEDGE (KNOWLEDGE_ID);



